Introduce predicate parameter for confitional exception mapping
khellang/Middleware pull request #131
Opened 2021-04-10 12:05 UTC by tibitoth

resolves #130 

I've implemented the API suggestion from the linked issue. The new test probably not the best looking but it covers the logic.

2021-04-10 18:37 UTC, khellang requested changes
This looks really good, just a few nits. Thanks again! 🙏🏻

2021-04-10 18:37 UTC, khellang commented on src/ProblemDetails/ProblemDetailsOptions.cs
> -        /// This will cause cause the exception to be rethrown.
Nice 😍

2021-04-10 18:37 UTC, khellang commented on src/ProblemDetails/ProblemDetailsOptions.cs
> +                if (CanMap(exception.GetType()) && Predicate(context, exception))
It feels cleaner to move the `Predicate` invocation into `CanMap`, maybe rename it to `ShouldMap`? 😅

2021-04-10 18:37 UTC, khellang commented on src/ProblemDetails/ProblemDetailsOptions.cs
> +                Predicate = predicate ?? throw new ArgumentNullException(nameof(predicate));
Can we throw for the other parameters as well? We obviously don't support passing `null` 😄

2021-04-11 10:48 UTC, tibitoth commented on src/ProblemDetails/ProblemDetailsOptions.cs
> +                if (CanMap(exception.GetType()) && Predicate(context, exception))
done

2021-04-11 10:48 UTC, tibitoth commented on src/ProblemDetails/ProblemDetailsOptions.cs
> +                Predicate = predicate ?? throw new ArgumentNullException(nameof(predicate));
done

2021-04-11 10:50 UTC, tibitoth commented
> This looks really good, just a few nits. Thanks again! 🙏🏻

Thanks for the review ;)

2021-04-11 17:55 UTC, khellang approved these changes

2021-04-11 17:55 UTC, merged

2021-04-11 17:57 UTC, khellang commented
Love it! 🥰 I'll try to get out a new version on NuGet ASAP 😊

2021-04-12 16:46 UTC, khellang commented
New version is on NuGet 😊