Removed netcoreapp3.1 and added net8.0 support
khellang/Middleware pull request #207
Opened 2024-10-16 22:20 UTC by armanossiloko

2024-10-24 22:18 UTC, armanossiloko commented
@khellang Did you plan on migrating your middleware repo to net8.0 and should I go on and close the PR if you prefer to keep things as they are?

2024-10-25 06:16 UTC, khellang requested changes
Thanks for the contribution! 🙏🏻  Just a few nits from me 😄

2024-10-25 06:16 UTC, khellang commented on src/ProblemDetails/ProblemDetails.csproj
> +    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
I think we can just remove .NET 6 as well. It's only a few weeks until it's out of support.

2024-10-25 06:16 UTC, khellang commented on src/SpaFallback/SpaFallback.csproj
> +  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
Is this necessary anymore?

2024-10-25 06:16 UTC, khellang commented on test/Directory.Build.props
> +    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
Same goes for these.

2024-10-25 06:16 UTC, khellang commented on Hellang.Middleware.sln
> -Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Authentication.JwtBearer.Google", "src\Authentication.JwtBearer.Google\Authentication.JwtBearer.Google.csproj", "{E5BCFA2D-ACE6-4BC6-A327-00956336
Why was this removed?

2024-10-25 09:15 UTC, armanossiloko commented on Hellang.Middleware.sln
> -Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Authentication.JwtBearer.Google", "src\Authentication.JwtBearer.Google\Authentication.JwtBearer.Google.csproj", "{E5BCFA2D-ACE6-4BC6-A327-00956336
I had it removed while doing the version changes and I thought I had re-added it, but I suppose not. It should be back in now.

2024-10-25 09:16 UTC, armanossiloko commented on test/Directory.Build.props
> +    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
Removed net6.0 support.

2024-10-25 09:17 UTC, armanossiloko commented on src/ProblemDetails/ProblemDetails.csproj
> +    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
I initially kept it in just for these last few weeks, but I think you're right - net6.0 support has been removed.

2024-10-25 10:24 UTC, armanossiloko commented on src/ProblemDetails/ProblemDetails.csproj
> +    <Version>7.0.0</Version>
Nice, thanks.

2024-10-25 10:37 UTC, khellang approved these changes

2024-10-25 10:46 UTC, khellang commented
Looks like the build failed because GitHub Actions only has the `8.0.402` SDK. Can we just try to remove the `global.json` entirely and go with the default?

2024-10-25 10:49 UTC, armanossiloko commented
> Looks like the build failed because GitHub Actions only has the `8.0.402` SDK. Can we just try to remove the `global.json` entirely and go with the default?

Absolutely. I've removed it now. Let's see how it goes.

2024-10-25 12:03 UTC, armanossiloko commented
lol Looks like the build is good now, but the SpaFallback tests are failing - guess changing the target framework to net8.0 was enough to break its behavior. :D

2024-10-25 21:39 UTC, khellang approved these changes

2024-10-25 21:40 UTC, merged

2024-10-25 21:40 UTC, khellang commented
Thanks for your awesome contribution, @armanossiloko! 🙏🏻